/* 🤖 this file was generated by svg-to-ts*/
export const libertyPlusIcon: {
  name: 'plus-icon';
  data: string;
} = {
  name: 'plus-icon',
  data: `<svg class="svg-rotate__icon" viewBox="0 0 357 357"><path d="M357 204H204v153h-51V204H0v-51h153V0h51v153h153v51z"/></svg>`
};
